@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage as StoragePackage {

package "UserPrefs Storage" #F4F6F6{
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

package "UserData Storage" {
Class "<<interface>>\nUserDataStorage" as UserDataStorage
Class JsonUserDataStorage
Class JsonSerializableUserData
Class JsonAdaptedUser
}

Class "<<interface>>\nStorage" as Storage
Class StorageManager

package "AddressBook Storage" #F4F6F6{
Class "<<interface>>\nAddressBookStorage" as AddressBookStorage
Class JsonAddressBookStorage
Class JsonSerializableAddressBook
Class JsonAdaptedPerson
Class JsonAdaptedTag


}
package "Timetable Classes"{
}
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" UserDataStorage
StorageManager -up-> "1" AddressBookStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> AddressBookStorage
Storage -right-|> UserDataStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonUserDataStorage .up.|> UserDataStorage
JsonAddressBookStorage .up.|> AddressBookStorage
JsonUserDataStorage ..> JsonSerializableUserData
JsonAddressBookStorage ..> JsonSerializableAddressBook
JsonSerializableUserData --> "1" JsonAdaptedUser
JsonSerializableAddressBook --> "*" JsonAdaptedPerson
JsonAdaptedPerson --> "*" JsonAdaptedTag
JsonAdaptedPerson --> "Timetable Classes"
JsonAdaptedUser --> "Timetable Classes"

@enduml
